// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/funding/v1/funding.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FundingMetadata struct {
	LastFundingRoundTimestamp int64 `protobuf:"varint,1,opt,name=last_funding_round_timestamp,json=lastFundingRoundTimestamp,proto3" json:"last_funding_round_timestamp,omitempty"`
	LastPremiumTimestamp      int64 `protobuf:"varint,2,opt,name=last_premium_timestamp,json=lastPremiumTimestamp,proto3" json:"last_premium_timestamp,omitempty"`
}

func (m *FundingMetadata) Reset()         { *m = FundingMetadata{} }
func (m *FundingMetadata) String() string { return proto.CompactTextString(m) }
func (*FundingMetadata) ProtoMessage()    {}
func (*FundingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_db56df8ae1077fac, []int{0}
}
func (m *FundingMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FundingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FundingMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FundingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundingMetadata.Merge(m, src)
}
func (m *FundingMetadata) XXX_Size() int {
	return m.Size()
}
func (m *FundingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FundingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FundingMetadata proto.InternalMessageInfo

func (m *FundingMetadata) GetLastFundingRoundTimestamp() int64 {
	if m != nil {
		return m.LastFundingRoundTimestamp
	}
	return 0
}

func (m *FundingMetadata) GetLastPremiumTimestamp() int64 {
	if m != nil {
		return m.LastPremiumTimestamp
	}
	return 0
}

type Params struct {
	FundingPeriodMs       int64  `protobuf:"varint,1,opt,name=funding_period_ms,json=fundingPeriodMs,proto3" json:"funding_period_ms,omitempty"`
	FundingPeriodDivisor  int64  `protobuf:"varint,2,opt,name=funding_period_divisor,json=fundingPeriodDivisor,proto3" json:"funding_period_divisor,omitempty"`
	MaxPremiumSampleCount uint32 `protobuf:"varint,3,opt,name=max_premium_sample_count,json=maxPremiumSampleCount,proto3" json:"max_premium_sample_count,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_db56df8ae1077fac, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFundingPeriodMs() int64 {
	if m != nil {
		return m.FundingPeriodMs
	}
	return 0
}

func (m *Params) GetFundingPeriodDivisor() int64 {
	if m != nil {
		return m.FundingPeriodDivisor
	}
	return 0
}

func (m *Params) GetMaxPremiumSampleCount() uint32 {
	if m != nil {
		return m.MaxPremiumSampleCount
	}
	return 0
}

func init() {
	proto.RegisterType((*FundingMetadata)(nil), "perpdex.funding.v1.FundingMetadata")
	proto.RegisterType((*Params)(nil), "perpdex.funding.v1.Params")
}

func init() { proto.RegisterFile("perpdex/funding/v1/funding.proto", fileDescriptor_db56df8ae1077fac) }

var fileDescriptor_db56df8ae1077fac = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x1c, 0xc6, 0x97, 0xdf, 0x60, 0x87, 0xc0, 0x8f, 0x61, 0x50, 0x99, 0x20, 0x61, 0xec, 0x34, 0x84,
	0xb5, 0x14, 0x05, 0x8f, 0x82, 0x8a, 0x9e, 0x06, 0xa5, 0x7a, 0xf2, 0x52, 0xb2, 0x25, 0xce, 0x40,
	0xd3, 0x84, 0x24, 0x2d, 0xf5, 0x1d, 0x78, 0xf4, 0x3d, 0xf8, 0x66, 0x3c, 0xee, 0xe8, 0x51, 0xda,
	0x37, 0x22, 0x6d, 0x93, 0xf9, 0xe7, 0x94, 0xe4, 0xfb, 0x7c, 0x9e, 0x3c, 0x5f, 0x78, 0xe0, 0x54,
	0x31, 0xad, 0x28, 0xab, 0xc2, 0xc7, 0x22, 0xa7, 0x3c, 0xdf, 0x84, 0x65, 0xe4, 0xaf, 0x81, 0xd2,
	0xd2, 0x4a, 0x84, 0x1c, 0x11, 0xf8, 0x71, 0x19, 0xcd, 0x5e, 0x00, 0x1c, 0xdf, 0xf4, 0xcf, 0x25,
	0xb3, 0x84, 0x12, 0x4b, 0xd0, 0x05, 0x3c, 0xce, 0x88, 0xb1, 0xa9, 0xc3, 0x52, 0x2d, 0x8b, 0x9c,
	0xa6, 0x96, 0x0b, 0x66, 0x2c, 0x11, 0x6a, 0x02, 0xa6, 0x60, 0x3e, 0x4c, 0x8e, 0x5a, 0xc6, 0x59,
	0x93, 0x96, 0xb8, 0xf7, 0x00, 0x3a, 0x83, 0x87, 0xdd, 0x07, 0x4a, 0x33, 0xc1, 0x0b, 0xf1, 0xc3,
	0xfa, 0xaf, 0xb3, 0xee, 0xb7, 0x6a, 0xdc, 0x8b, 0x3b, 0xd7, 0xec, 0x0d, 0xc0, 0x51, 0x4c, 0x34,
	0x11, 0x06, 0x9d, 0xc0, 0x3d, 0x1f, 0xae, 0x98, 0xe6, 0x92, 0xa6, 0xc2, 0xb8, 0xd8, 0xb1, 0x13,
	0xe2, 0x6e, 0xbe, 0x34, 0x6d, 0xd8, 0x1f, 0x96, 0xf2, 0x92, 0x1b, 0xa9, 0x7d, 0xd8, 0x2f, 0xc3,
	0x75, 0xaf, 0xa1, 0x73, 0x38, 0x11, 0xa4, 0xda, 0x6d, 0x68, 0x88, 0x50, 0x19, 0x4b, 0xd7, 0xb2,
	0xc8, 0xed, 0x64, 0x38, 0x05, 0xf3, 0xff, 0xc9, 0x81, 0x20, 0x95, 0xdb, 0xf1, 0xae, 0x53, 0xaf,
	0x5a, 0xf1, 0xf2, 0xf6, 0xbd, 0xc6, 0x60, 0x5b, 0x63, 0xf0, 0x59, 0x63, 0xf0, 0xda, 0xe0, 0xc1,
	0xb6, 0xc1, 0x83, 0x8f, 0x06, 0x0f, 0x1e, 0x16, 0x1b, 0x6e, 0x9f, 0x8a, 0x55, 0xb0, 0x96, 0x22,
	0xf4, 0x5d, 0xb8, 0x73, 0x91, 0x45, 0xe1, 0x77, 0x31, 0xf6, 0x59, 0x31, 0xb3, 0x1a, 0x75, 0xa5,
	0x9c, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x23, 0x6f, 0x57, 0xb8, 0x01, 0x00, 0x00,
}

func (m *FundingMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FundingMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FundingMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastPremiumTimestamp != 0 {
		i = encodeVarintFunding(dAtA, i, uint64(m.LastPremiumTimestamp))
		i--
		dAtA[i] = 0x10
	}
	if m.LastFundingRoundTimestamp != 0 {
		i = encodeVarintFunding(dAtA, i, uint64(m.LastFundingRoundTimestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxPremiumSampleCount != 0 {
		i = encodeVarintFunding(dAtA, i, uint64(m.MaxPremiumSampleCount))
		i--
		dAtA[i] = 0x18
	}
	if m.FundingPeriodDivisor != 0 {
		i = encodeVarintFunding(dAtA, i, uint64(m.FundingPeriodDivisor))
		i--
		dAtA[i] = 0x10
	}
	if m.FundingPeriodMs != 0 {
		i = encodeVarintFunding(dAtA, i, uint64(m.FundingPeriodMs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFunding(dAtA []byte, offset int, v uint64) int {
	offset -= sovFunding(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FundingMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastFundingRoundTimestamp != 0 {
		n += 1 + sovFunding(uint64(m.LastFundingRoundTimestamp))
	}
	if m.LastPremiumTimestamp != 0 {
		n += 1 + sovFunding(uint64(m.LastPremiumTimestamp))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FundingPeriodMs != 0 {
		n += 1 + sovFunding(uint64(m.FundingPeriodMs))
	}
	if m.FundingPeriodDivisor != 0 {
		n += 1 + sovFunding(uint64(m.FundingPeriodDivisor))
	}
	if m.MaxPremiumSampleCount != 0 {
		n += 1 + sovFunding(uint64(m.MaxPremiumSampleCount))
	}
	return n
}

func sovFunding(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFunding(x uint64) (n int) {
	return sovFunding(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FundingMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFunding
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FundingMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FundingMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastFundingRoundTimestamp", wireType)
			}
			m.LastFundingRoundTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastFundingRoundTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPremiumTimestamp", wireType)
			}
			m.LastPremiumTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPremiumTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFunding(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFunding
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFunding
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingPeriodMs", wireType)
			}
			m.FundingPeriodMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FundingPeriodMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingPeriodDivisor", wireType)
			}
			m.FundingPeriodDivisor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FundingPeriodDivisor |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPremiumSampleCount", wireType)
			}
			m.MaxPremiumSampleCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPremiumSampleCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFunding(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFunding
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFunding(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFunding
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFunding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFunding
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFunding
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFunding
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFunding        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFunding          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFunding = fmt.Errorf("proto: unexpected end of group")
)
