// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/liquidation/v1/liquidation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidationFlag struct {
	AccountIndex   uint64 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	MarketIndex    uint32 `protobuf:"varint,2,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	FlaggedAtBlock int64  `protobuf:"varint,3,opt,name=flagged_at_block,json=flaggedAtBlock,proto3" json:"flagged_at_block,omitempty"`
	FlaggedAtTime  int64  `protobuf:"varint,4,opt,name=flagged_at_time,json=flaggedAtTime,proto3" json:"flagged_at_time,omitempty"`
}

func (m *LiquidationFlag) Reset()         { *m = LiquidationFlag{} }
func (m *LiquidationFlag) String() string { return proto.CompactTextString(m) }
func (*LiquidationFlag) ProtoMessage()    {}
func (*LiquidationFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_355eeec9cda6bf86, []int{0}
}
func (m *LiquidationFlag) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationFlag.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationFlag.Merge(m, src)
}
func (m *LiquidationFlag) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationFlag.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationFlag proto.InternalMessageInfo

func (m *LiquidationFlag) GetAccountIndex() uint64 {
	if m != nil {
		return m.AccountIndex
	}
	return 0
}

func (m *LiquidationFlag) GetMarketIndex() uint32 {
	if m != nil {
		return m.MarketIndex
	}
	return 0
}

func (m *LiquidationFlag) GetFlaggedAtBlock() int64 {
	if m != nil {
		return m.FlaggedAtBlock
	}
	return 0
}

func (m *LiquidationFlag) GetFlaggedAtTime() int64 {
	if m != nil {
		return m.FlaggedAtTime
	}
	return 0
}

type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_355eeec9cda6bf86, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LiquidationFlag)(nil), "perpdex.liquidation.v1.LiquidationFlag")
	proto.RegisterType((*Params)(nil), "perpdex.liquidation.v1.Params")
}

func init() {
	proto.RegisterFile("perpdex/liquidation/v1/liquidation.proto", fileDescriptor_355eeec9cda6bf86)
}

var fileDescriptor_355eeec9cda6bf86 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x48, 0x2d, 0x2a,
	0x48, 0x49, 0xad, 0xd0, 0xcf, 0xc9, 0x2c, 0x2c, 0xcd, 0x4c, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3,
	0x2f, 0x33, 0x44, 0xe6, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x89, 0x41, 0x55, 0xea, 0x21,
	0x4b, 0x95, 0x19, 0x2a, 0xad, 0x66, 0xe4, 0xe2, 0xf7, 0x41, 0x08, 0xb9, 0xe5, 0x24, 0xa6, 0x0b,
	0x29, 0x73, 0xf1, 0x26, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0xc4, 0x67, 0xe6, 0xa5, 0xa4, 0x56,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xf1, 0x40, 0x05, 0x3d, 0x41, 0x62, 0x42, 0x8a, 0x5c,
	0x3c, 0xb9, 0x89, 0x45, 0xd9, 0xa9, 0x30, 0x35, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0xdc, 0x10,
	0x31, 0x88, 0x12, 0x0d, 0x2e, 0x81, 0xb4, 0x9c, 0xc4, 0xf4, 0xf4, 0xd4, 0x94, 0xf8, 0xc4, 0x92,
	0xf8, 0xa4, 0x9c, 0xfc, 0xe4, 0x6c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x3e, 0xa8, 0xb8,
	0x63, 0x89, 0x13, 0x48, 0x54, 0x48, 0x8d, 0x8b, 0x1f, 0x49, 0x65, 0x49, 0x66, 0x6e, 0xaa, 0x04,
	0x0b, 0x58, 0x21, 0x2f, 0x5c, 0x61, 0x48, 0x66, 0x6e, 0xaa, 0x12, 0x07, 0x17, 0x5b, 0x40, 0x62,
	0x51, 0x62, 0x6e, 0xb1, 0x93, 0xf7, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78,
	0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44,
	0x19, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xc3, 0x82, 0x07, 0x4a,
	0xeb, 0xe6, 0x18, 0xea, 0xa3, 0x86, 0x55, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0x38, 0x8c,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x7e, 0x2b, 0x09, 0x4f, 0x01, 0x00, 0x00,
}

func (m *LiquidationFlag) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationFlag) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationFlag) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FlaggedAtTime != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.FlaggedAtTime))
		i--
		dAtA[i] = 0x20
	}
	if m.FlaggedAtBlock != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.FlaggedAtBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.MarketIndex != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.MarketIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.AccountIndex != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.AccountIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintLiquidation(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidationFlag) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountIndex != 0 {
		n += 1 + sovLiquidation(uint64(m.AccountIndex))
	}
	if m.MarketIndex != 0 {
		n += 1 + sovLiquidation(uint64(m.MarketIndex))
	}
	if m.FlaggedAtBlock != 0 {
		n += 1 + sovLiquidation(uint64(m.FlaggedAtBlock))
	}
	if m.FlaggedAtTime != 0 {
		n += 1 + sovLiquidation(uint64(m.FlaggedAtTime))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovLiquidation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidation(x uint64) (n int) {
	return sovLiquidation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidationFlag) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationFlag: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationFlag: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountIndex", wireType)
			}
			m.AccountIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIndex", wireType)
			}
			m.MarketIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlaggedAtBlock", wireType)
			}
			m.FlaggedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FlaggedAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlaggedAtTime", wireType)
			}
			m.FlaggedAtTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FlaggedAtTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidation = fmt.Errorf("proto: unexpected end of group")
)
