// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/liquidation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryLiquidationFlagRequest struct {
	AccountIndex uint64 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	MarketIndex  uint32 `protobuf:"varint,2,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
}

func (m *QueryLiquidationFlagRequest) Reset()         { *m = QueryLiquidationFlagRequest{} }
func (m *QueryLiquidationFlagRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationFlagRequest) ProtoMessage()    {}
func (*QueryLiquidationFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{2}
}
func (m *QueryLiquidationFlagRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidationFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidationFlagRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidationFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationFlagRequest.Merge(m, src)
}
func (m *QueryLiquidationFlagRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidationFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationFlagRequest proto.InternalMessageInfo

func (m *QueryLiquidationFlagRequest) GetAccountIndex() uint64 {
	if m != nil {
		return m.AccountIndex
	}
	return 0
}

func (m *QueryLiquidationFlagRequest) GetMarketIndex() uint32 {
	if m != nil {
		return m.MarketIndex
	}
	return 0
}

type QueryLiquidationFlagResponse struct {
	// present is false when the (account, market) pair is not flagged.
	Present bool            `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Flag    LiquidationFlag `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag"`
}

func (m *QueryLiquidationFlagResponse) Reset()         { *m = QueryLiquidationFlagResponse{} }
func (m *QueryLiquidationFlagResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationFlagResponse) ProtoMessage()    {}
func (*QueryLiquidationFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{3}
}
func (m *QueryLiquidationFlagResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidationFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidationFlagResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidationFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationFlagResponse.Merge(m, src)
}
func (m *QueryLiquidationFlagResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidationFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationFlagResponse proto.InternalMessageInfo

func (m *QueryLiquidationFlagResponse) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

func (m *QueryLiquidationFlagResponse) GetFlag() LiquidationFlag {
	if m != nil {
		return m.Flag
	}
	return LiquidationFlag{}
}

type QueryLiquidationFlagsRequest struct {
	AccountIndex uint64 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
}

func (m *QueryLiquidationFlagsRequest) Reset()         { *m = QueryLiquidationFlagsRequest{} }
func (m *QueryLiquidationFlagsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationFlagsRequest) ProtoMessage()    {}
func (*QueryLiquidationFlagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{4}
}
func (m *QueryLiquidationFlagsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidationFlagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidationFlagsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidationFlagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationFlagsRequest.Merge(m, src)
}
func (m *QueryLiquidationFlagsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidationFlagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationFlagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationFlagsRequest proto.InternalMessageInfo

func (m *QueryLiquidationFlagsRequest) GetAccountIndex() uint64 {
	if m != nil {
		return m.AccountIndex
	}
	return 0
}

type QueryLiquidationFlagsResponse struct {
	Flags []LiquidationFlag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags"`
}

func (m *QueryLiquidationFlagsResponse) Reset()         { *m = QueryLiquidationFlagsResponse{} }
func (m *QueryLiquidationFlagsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationFlagsResponse) ProtoMessage()    {}
func (*QueryLiquidationFlagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca7601e3ca4d856, []int{5}
}
func (m *QueryLiquidationFlagsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLiquidationFlagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLiquidationFlagsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLiquidationFlagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationFlagsResponse.Merge(m, src)
}
func (m *QueryLiquidationFlagsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLiquidationFlagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationFlagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationFlagsResponse proto.InternalMessageInfo

func (m *QueryLiquidationFlagsResponse) GetFlags() []LiquidationFlag {
	if m != nil {
		return m.Flags
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "perpdex.liquidation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "perpdex.liquidation.v1.QueryParamsResponse")
	proto.RegisterType((*QueryLiquidationFlagRequest)(nil), "perpdex.liquidation.v1.QueryLiquidationFlagRequest")
	proto.RegisterType((*QueryLiquidationFlagResponse)(nil), "perpdex.liquidation.v1.QueryLiquidationFlagResponse")
	proto.RegisterType((*QueryLiquidationFlagsRequest)(nil), "perpdex.liquidation.v1.QueryLiquidationFlagsRequest")
	proto.RegisterType((*QueryLiquidationFlagsResponse)(nil), "perpdex.liquidation.v1.QueryLiquidationFlagsResponse")
}

func init() {
	proto.RegisterFile("perpdex/liquidation/v1/query.proto", fileDescriptor_eca7601e3ca4d856)
}

var fileDescriptor_eca7601e3ca4d856 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0xaf, 0x47, 0x57, 0xd0, 0xeb, 0x26, 0x90, 0x99, 0xd0, 0x54, 0x86, 0x29, 0x46, 0x82, 0x0a,
	0xb4, 0x58, 0xed, 0xd8, 0x09, 0x38, 0xb0, 0x4a, 0x48, 0x08, 0x0e, 0x10, 0x6e, 0x5c, 0x90, 0xd7,
	0x9a, 0x10, 0x91, 0xc6, 0x6e, 0xec, 0x4c, 0x9b, 0xaa, 0x5d, 0xb8, 0x71, 0x9b, 0xc4, 0x77, 0xe1,
	0xce, 0x6d, 0xc7, 0x49, 0x5c, 0x38, 0x21, 0xd4, 0xf2, 0x41, 0x50, 0x1c, 0x6f, 0xb4, 0xa5, 0x99,
	0x96, 0x53, 0x92, 0x97, 0xdf, 0xfb, 0xfd, 0xf1, 0x7b, 0x32, 0x50, 0x25, 0x12, 0xd5, 0x17, 0xfb,
	0x2c, 0x0a, 0x87, 0x69, 0xd8, 0xe7, 0x26, 0x94, 0x31, 0xdb, 0x6b, 0xb3, 0x61, 0x2a, 0x92, 0x03,
	0x4f, 0x25, 0xd2, 0x48, 0x7c, 0xc3, 0x61, 0xbc, 0x29, 0x8c, 0xb7, 0xd7, 0x6e, 0xac, 0x05, 0x32,
	0x90, 0x16, 0xc2, 0xb2, 0xb7, 0x1c, 0xdd, 0xd8, 0x08, 0xa4, 0x0c, 0x22, 0xc1, 0xb8, 0x0a, 0x19,
	0x8f, 0x63, 0x69, 0x2c, 0x5e, 0xbb, 0xbf, 0xad, 0x02, 0xbd, 0x69, 0x6a, 0x8b, 0xa4, 0x6b, 0x80,
	0xdf, 0x64, 0x26, 0x5e, 0xf3, 0x84, 0x0f, 0xb4, 0x2f, 0x86, 0xa9, 0xd0, 0x86, 0xbe, 0x85, 0xeb,
	0x33, 0x55, 0xad, 0x64, 0xac, 0x05, 0x7e, 0x02, 0x35, 0x65, 0x2b, 0xeb, 0xa8, 0x89, 0x5a, 0xf5,
	0x0e, 0xf1, 0x16, 0x7b, 0xf6, 0xf2, 0xbe, 0x9d, 0xea, 0xf1, 0xaf, 0xdb, 0x15, 0xdf, 0xf5, 0x50,
	0x01, 0x37, 0x2d, 0xe9, 0xab, 0x7f, 0xd8, 0xe7, 0x11, 0x0f, 0x9c, 0x26, 0xbe, 0x0b, 0xab, 0xbc,
	0xd7, 0x93, 0x69, 0x6c, 0xde, 0x87, 0x71, 0x5f, 0xec, 0x5b, 0x8d, 0xaa, 0xbf, 0xe2, 0x8a, 0x2f,
	0xb2, 0x1a, 0xbe, 0x03, 0x2b, 0x03, 0x9e, 0x7c, 0x12, 0xa7, 0x98, 0xa5, 0x26, 0x6a, 0xad, 0xfa,
	0xf5, 0xbc, 0x66, 0x21, 0x74, 0x04, 0x1b, 0x8b, 0x65, 0x5c, 0x88, 0x75, 0xb8, 0xac, 0x12, 0xa1,
	0x45, 0x6c, 0xac, 0xc2, 0x15, 0xff, 0xf4, 0x13, 0x3f, 0x83, 0xea, 0x87, 0x88, 0x07, 0x96, 0xb4,
	0xde, 0xb9, 0x5f, 0x14, 0x6e, 0x8e, 0xd8, 0xa5, 0xb4, 0xad, 0xb4, 0xbb, 0x58, 0x5c, 0x97, 0x09,
	0x49, 0xfb, 0x70, 0xab, 0x80, 0xc4, 0x45, 0xe8, 0xc2, 0x72, 0xa6, 0x96, 0x8d, 0xe1, 0x52, 0x79,
	0xa7, 0x79, 0x6f, 0xe7, 0xa8, 0x0a, 0xcb, 0x56, 0x06, 0x7f, 0x41, 0x50, 0xcb, 0x27, 0x86, 0x1f,
	0x14, 0x51, 0xfd, 0xbf, 0x24, 0x8d, 0x87, 0x17, 0xc2, 0xe6, 0x96, 0xe9, 0xbd, 0xcf, 0x3f, 0xfe,
	0x7c, 0x5d, 0x6a, 0x62, 0xc2, 0x0a, 0x56, 0x33, 0x5f, 0x12, 0xfc, 0x1d, 0xc1, 0xd5, 0x39, 0xdb,
	0x78, 0xeb, 0x5c, 0xa1, 0xc5, 0xeb, 0xd4, 0x78, 0x54, 0xae, 0xc9, 0xd9, 0xec, 0x5a, 0x9b, 0x4f,
	0xf1, 0xe3, 0x22, 0x9b, 0xd9, 0xd9, 0xb1, 0xd1, 0xcc, 0x0c, 0x0f, 0xd9, 0x68, 0x7a, 0x27, 0x0f,
	0xf1, 0x37, 0x04, 0xd7, 0xe6, 0x67, 0x87, 0x4b, 0xf9, 0x39, 0x3b, 0xe3, 0xed, 0x92, 0x5d, 0x2e,
	0xc6, 0xb6, 0x8d, 0xc1, 0xf0, 0xe6, 0x79, 0x31, 0xf4, 0x7c, 0x8e, 0x9d, 0x97, 0xc7, 0x63, 0x82,
	0x4e, 0xc6, 0x04, 0xfd, 0x1e, 0x13, 0x74, 0x34, 0x21, 0x95, 0x93, 0x09, 0xa9, 0xfc, 0x9c, 0x90,
	0xca, 0xbb, 0x76, 0x10, 0x9a, 0x8f, 0xe9, 0xae, 0xd7, 0x93, 0x83, 0x33, 0x4a, 0xf7, 0xdc, 0x8c,
	0xda, 0x6c, 0x96, 0xdf, 0x1c, 0x28, 0xa1, 0x77, 0x6b, 0xf6, 0x82, 0xd9, 0xfa, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xc7, 0xb6, 0xbf, 0xfb, 0xfc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LiquidationFlag returns the flag for a single (account, market). The
	// EndBlocker writes flags every block while an account remains
	// unhealthy and clears them once it returns to HEALTHY.
	LiquidationFlag(ctx context.Context, in *QueryLiquidationFlagRequest, opts ...grpc.CallOption) (*QueryLiquidationFlagResponse, error)
	// LiquidationFlags lists every flag currently set for the given
	// account. Useful for keeper bots scanning a victim's positions.
	LiquidationFlags(ctx context.Context, in *QueryLiquidationFlagsRequest, opts ...grpc.CallOption) (*QueryLiquidationFlagsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.liquidation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LiquidationFlag(ctx context.Context, in *QueryLiquidationFlagRequest, opts ...grpc.CallOption) (*QueryLiquidationFlagResponse, error) {
	out := new(QueryLiquidationFlagResponse)
	err := c.cc.Invoke(ctx, "/perpdex.liquidation.v1.Query/LiquidationFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LiquidationFlags(ctx context.Context, in *QueryLiquidationFlagsRequest, opts ...grpc.CallOption) (*QueryLiquidationFlagsResponse, error) {
	out := new(QueryLiquidationFlagsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.liquidation.v1.Query/LiquidationFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LiquidationFlag returns the flag for a single (account, market). The
	// EndBlocker writes flags every block while an account remains
	// unhealthy and clears them once it returns to HEALTHY.
	LiquidationFlag(context.Context, *QueryLiquidationFlagRequest) (*QueryLiquidationFlagResponse, error)
	// LiquidationFlags lists every flag currently set for the given
	// account. Useful for keeper bots scanning a victim's positions.
	LiquidationFlags(context.Context, *QueryLiquidationFlagsRequest) (*QueryLiquidationFlagsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LiquidationFlag(ctx context.Context, req *QueryLiquidationFlagRequest) (*QueryLiquidationFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidationFlag not implemented")
}
func (*UnimplementedQueryServer) LiquidationFlags(ctx context.Context, req *QueryLiquidationFlagsRequest) (*QueryLiquidationFlagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidationFlags not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.liquidation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LiquidationFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLiquidationFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LiquidationFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.liquidation.v1.Query/LiquidationFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LiquidationFlag(ctx, req.(*QueryLiquidationFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LiquidationFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLiquidationFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LiquidationFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.liquidation.v1.Query/LiquidationFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LiquidationFlags(ctx, req.(*QueryLiquidationFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.liquidation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LiquidationFlag",
			Handler:    _Query_LiquidationFlag_Handler,
		},
		{
			MethodName: "LiquidationFlags",
			Handler:    _Query_LiquidationFlags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/liquidation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLiquidationFlagRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidationFlagRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidationFlagRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarketIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MarketIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.AccountIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AccountIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidationFlagResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidationFlagResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidationFlagResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Flag.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Present {
		i--
		if m.Present {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidationFlagsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidationFlagsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidationFlagsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AccountIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLiquidationFlagsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLiquidationFlagsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLiquidationFlagsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Flags) > 0 {
		for iNdEx := len(m.Flags) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Flags[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLiquidationFlagRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountIndex != 0 {
		n += 1 + sovQuery(uint64(m.AccountIndex))
	}
	if m.MarketIndex != 0 {
		n += 1 + sovQuery(uint64(m.MarketIndex))
	}
	return n
}

func (m *QueryLiquidationFlagResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Present {
		n += 2
	}
	l = m.Flag.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLiquidationFlagsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountIndex != 0 {
		n += 1 + sovQuery(uint64(m.AccountIndex))
	}
	return n
}

func (m *QueryLiquidationFlagsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Flags) > 0 {
		for _, e := range m.Flags {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidationFlagRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidationFlagRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidationFlagRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountIndex", wireType)
			}
			m.AccountIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIndex", wireType)
			}
			m.MarketIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidationFlagResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidationFlagResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidationFlagResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Present", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Present = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Flag.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidationFlagsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidationFlagsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidationFlagsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountIndex", wireType)
			}
			m.AccountIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLiquidationFlagsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLiquidationFlagsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLiquidationFlagsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flags = append(m.Flags, LiquidationFlag{})
			if err := m.Flags[len(m.Flags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
