// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/orderbook/v1/orderbook.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	OrderIndex          uint64 `protobuf:"varint,1,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	ClientOrderIndex    uint64 `protobuf:"varint,2,opt,name=client_order_index,json=clientOrderIndex,proto3" json:"client_order_index,omitempty"`
	OwnerAccountIndex   uint64 `protobuf:"varint,3,opt,name=owner_account_index,json=ownerAccountIndex,proto3" json:"owner_account_index,omitempty"`
	MarketIndex         uint32 `protobuf:"varint,4,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	IsAsk               bool   `protobuf:"varint,5,opt,name=is_ask,json=isAsk,proto3" json:"is_ask,omitempty"`
	OrderType           uint32 `protobuf:"varint,6,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	TimeInForce         uint32 `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	ReduceOnly          bool   `protobuf:"varint,8,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	Price               uint32 `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	Nonce               int64  `protobuf:"varint,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	InitialBaseAmount   uint64 `protobuf:"varint,11,opt,name=initial_base_amount,json=initialBaseAmount,proto3" json:"initial_base_amount,omitempty"`
	RemainingBaseAmount uint64 `protobuf:"varint,12,opt,name=remaining_base_amount,json=remainingBaseAmount,proto3" json:"remaining_base_amount,omitempty"`
	TriggerPrice        uint32 `protobuf:"varint,13,opt,name=trigger_price,json=triggerPrice,proto3" json:"trigger_price,omitempty"`
	TriggerStatus       uint32 `protobuf:"varint,14,opt,name=trigger_status,json=triggerStatus,proto3" json:"trigger_status,omitempty"`
	Expiry              int64  `protobuf:"varint,15,opt,name=expiry,proto3" json:"expiry,omitempty"`
	CreatedAt           int64  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status              uint32 `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6faf1dc2a4714d16, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Order.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return m.Size()
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderIndex() uint64 {
	if m != nil {
		return m.OrderIndex
	}
	return 0
}

func (m *Order) GetClientOrderIndex() uint64 {
	if m != nil {
		return m.ClientOrderIndex
	}
	return 0
}

func (m *Order) GetOwnerAccountIndex() uint64 {
	if m != nil {
		return m.OwnerAccountIndex
	}
	return 0
}

func (m *Order) GetMarketIndex() uint32 {
	if m != nil {
		return m.MarketIndex
	}
	return 0
}

func (m *Order) GetIsAsk() bool {
	if m != nil {
		return m.IsAsk
	}
	return false
}

func (m *Order) GetOrderType() uint32 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func (m *Order) GetTimeInForce() uint32 {
	if m != nil {
		return m.TimeInForce
	}
	return 0
}

func (m *Order) GetReduceOnly() bool {
	if m != nil {
		return m.ReduceOnly
	}
	return false
}

func (m *Order) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Order) GetInitialBaseAmount() uint64 {
	if m != nil {
		return m.InitialBaseAmount
	}
	return 0
}

func (m *Order) GetRemainingBaseAmount() uint64 {
	if m != nil {
		return m.RemainingBaseAmount
	}
	return 0
}

func (m *Order) GetTriggerPrice() uint32 {
	if m != nil {
		return m.TriggerPrice
	}
	return 0
}

func (m *Order) GetTriggerStatus() uint32 {
	if m != nil {
		return m.TriggerStatus
	}
	return 0
}

func (m *Order) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type OrderBookEntry struct {
	OrderIndex          uint64 `protobuf:"varint,1,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	OwnerAccountIndex   uint64 `protobuf:"varint,2,opt,name=owner_account_index,json=ownerAccountIndex,proto3" json:"owner_account_index,omitempty"`
	Price               uint32 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Nonce               int64  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	RemainingBaseAmount uint64 `protobuf:"varint,5,opt,name=remaining_base_amount,json=remainingBaseAmount,proto3" json:"remaining_base_amount,omitempty"`
	Expiry              int64  `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	IsPostOnly          bool   `protobuf:"varint,7,opt,name=is_post_only,json=isPostOnly,proto3" json:"is_post_only,omitempty"`
	ReduceOnly          bool   `protobuf:"varint,8,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	OrderType           uint32 `protobuf:"varint,9,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
}

func (m *OrderBookEntry) Reset()         { *m = OrderBookEntry{} }
func (m *OrderBookEntry) String() string { return proto.CompactTextString(m) }
func (*OrderBookEntry) ProtoMessage()    {}
func (*OrderBookEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6faf1dc2a4714d16, []int{1}
}
func (m *OrderBookEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderBookEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderBookEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderBookEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookEntry.Merge(m, src)
}
func (m *OrderBookEntry) XXX_Size() int {
	return m.Size()
}
func (m *OrderBookEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookEntry proto.InternalMessageInfo

func (m *OrderBookEntry) GetOrderIndex() uint64 {
	if m != nil {
		return m.OrderIndex
	}
	return 0
}

func (m *OrderBookEntry) GetOwnerAccountIndex() uint64 {
	if m != nil {
		return m.OwnerAccountIndex
	}
	return 0
}

func (m *OrderBookEntry) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderBookEntry) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *OrderBookEntry) GetRemainingBaseAmount() uint64 {
	if m != nil {
		return m.RemainingBaseAmount
	}
	return 0
}

func (m *OrderBookEntry) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *OrderBookEntry) GetIsPostOnly() bool {
	if m != nil {
		return m.IsPostOnly
	}
	return false
}

func (m *OrderBookEntry) GetReduceOnly() bool {
	if m != nil {
		return m.ReduceOnly
	}
	return false
}

func (m *OrderBookEntry) GetOrderType() uint32 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

type PriceLevelAggregate struct {
	MarketIndex uint32 `protobuf:"varint,1,opt,name=market_index,json=marketIndex,proto3" json:"market_index,omitempty"`
	Price       uint32 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	AskBaseSum  uint64 `protobuf:"varint,3,opt,name=ask_base_sum,json=askBaseSum,proto3" json:"ask_base_sum,omitempty"`
	AskQuoteSum uint64 `protobuf:"varint,4,opt,name=ask_quote_sum,json=askQuoteSum,proto3" json:"ask_quote_sum,omitempty"`
	BidBaseSum  uint64 `protobuf:"varint,5,opt,name=bid_base_sum,json=bidBaseSum,proto3" json:"bid_base_sum,omitempty"`
	BidQuoteSum uint64 `protobuf:"varint,6,opt,name=bid_quote_sum,json=bidQuoteSum,proto3" json:"bid_quote_sum,omitempty"`
	AskCount    uint32 `protobuf:"varint,7,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	BidCount    uint32 `protobuf:"varint,8,opt,name=bid_count,json=bidCount,proto3" json:"bid_count,omitempty"`
}

func (m *PriceLevelAggregate) Reset()         { *m = PriceLevelAggregate{} }
func (m *PriceLevelAggregate) String() string { return proto.CompactTextString(m) }
func (*PriceLevelAggregate) ProtoMessage()    {}
func (*PriceLevelAggregate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6faf1dc2a4714d16, []int{2}
}
func (m *PriceLevelAggregate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceLevelAggregate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceLevelAggregate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceLevelAggregate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceLevelAggregate.Merge(m, src)
}
func (m *PriceLevelAggregate) XXX_Size() int {
	return m.Size()
}
func (m *PriceLevelAggregate) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceLevelAggregate.DiscardUnknown(m)
}

var xxx_messageInfo_PriceLevelAggregate proto.InternalMessageInfo

func (m *PriceLevelAggregate) GetMarketIndex() uint32 {
	if m != nil {
		return m.MarketIndex
	}
	return 0
}

func (m *PriceLevelAggregate) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PriceLevelAggregate) GetAskBaseSum() uint64 {
	if m != nil {
		return m.AskBaseSum
	}
	return 0
}

func (m *PriceLevelAggregate) GetAskQuoteSum() uint64 {
	if m != nil {
		return m.AskQuoteSum
	}
	return 0
}

func (m *PriceLevelAggregate) GetBidBaseSum() uint64 {
	if m != nil {
		return m.BidBaseSum
	}
	return 0
}

func (m *PriceLevelAggregate) GetBidQuoteSum() uint64 {
	if m != nil {
		return m.BidQuoteSum
	}
	return 0
}

func (m *PriceLevelAggregate) GetAskCount() uint32 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *PriceLevelAggregate) GetBidCount() uint32 {
	if m != nil {
		return m.BidCount
	}
	return 0
}

// Params is reserved for future orderbook-only governance knobs. The
// historical fields have all been retired:
//   - max_fills_per_msg / max_cancels_per_msg: live limits now on
//     x/matching.Params.
//   - impact_usdc_amount: replaced by the per-market derivation
//     `IMPACT_USDC * MARGIN_TICK / min_initial_margin_fraction` in
//     ComputeImpactPrice.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6faf1dc2a4714d16, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Order)(nil), "perpdex.orderbook.v1.Order")
	proto.RegisterType((*OrderBookEntry)(nil), "perpdex.orderbook.v1.OrderBookEntry")
	proto.RegisterType((*PriceLevelAggregate)(nil), "perpdex.orderbook.v1.PriceLevelAggregate")
	proto.RegisterType((*Params)(nil), "perpdex.orderbook.v1.Params")
}

func init() {
	proto.RegisterFile("perpdex/orderbook/v1/orderbook.proto", fileDescriptor_6faf1dc2a4714d16)
}

var fileDescriptor_6faf1dc2a4714d16 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0xd3, 0xc4, 0x4d, 0x6e, 0x92, 0x7e, 0xad, 0xdb, 0x7e, 0xb2, 0x54, 0x11, 0x4c, 0x00,
	0x29, 0x0b, 0x48, 0x54, 0x78, 0x82, 0x14, 0x81, 0x54, 0x09, 0xa9, 0x25, 0x65, 0xc5, 0xc6, 0x1a,
	0xdb, 0x83, 0x19, 0x39, 0x9e, 0x31, 0x33, 0xe3, 0xd2, 0xbc, 0x05, 0x0b, 0xde, 0x86, 0x17, 0x60,
	0x47, 0x97, 0x2c, 0x51, 0xfb, 0x22, 0x68, 0xee, 0x38, 0x3f, 0xa5, 0x44, 0x5d, 0x45, 0x73, 0xce,
	0xb9, 0x37, 0x73, 0xcf, 0x9c, 0x6b, 0x78, 0x52, 0x50, 0x59, 0x24, 0xf4, 0x72, 0x24, 0x64, 0x42,
	0x65, 0x24, 0x44, 0x36, 0xba, 0x38, 0x5a, 0x1e, 0x86, 0x85, 0x14, 0x5a, 0x78, 0xfb, 0x95, 0x6a,
	0xb8, 0x24, 0x2e, 0x8e, 0xfa, 0x3f, 0xeb, 0xd0, 0x38, 0x35, 0x80, 0xf7, 0x10, 0xda, 0xc8, 0x84,
	0x8c, 0x27, 0xf4, 0xd2, 0x77, 0x02, 0x67, 0x50, 0x9f, 0x00, 0x42, 0x27, 0x06, 0xf1, 0x9e, 0x81,
	0x17, 0x4f, 0x19, 0xe5, 0x3a, 0x5c, 0xd5, 0xd5, 0x50, 0xb7, 0x63, 0x99, 0xd3, 0xa5, 0x7a, 0x08,
	0x7b, 0xe2, 0x0b, 0xa7, 0x32, 0x24, 0x71, 0x2c, 0x4a, 0xae, 0x2b, 0xf9, 0x26, 0xca, 0x77, 0x91,
	0x1a, 0x5b, 0xc6, 0xea, 0x1f, 0x41, 0x27, 0x27, 0x32, 0xa3, 0x73, 0x61, 0x3d, 0x70, 0x06, 0xdd,
	0x49, 0xdb, 0x62, 0x56, 0x72, 0x00, 0x2e, 0x53, 0x21, 0x51, 0x99, 0xdf, 0x08, 0x9c, 0x41, 0x73,
	0xd2, 0x60, 0x6a, 0xac, 0x32, 0xef, 0x01, 0xd8, 0x5b, 0x86, 0x7a, 0x56, 0x50, 0xdf, 0xc5, 0xba,
	0x16, 0x22, 0xef, 0x67, 0x05, 0xf5, 0xfa, 0xd0, 0xd5, 0x2c, 0xa7, 0x21, 0xe3, 0xe1, 0x47, 0x21,
	0x63, 0xea, 0x6f, 0xd9, 0xce, 0x06, 0x3c, 0xe1, 0x6f, 0x0c, 0x64, 0x66, 0x97, 0x34, 0x29, 0x63,
	0x1a, 0x0a, 0x3e, 0x9d, 0xf9, 0x4d, 0x6c, 0x0f, 0x16, 0x3a, 0xe5, 0xd3, 0x99, 0xb7, 0x0f, 0x8d,
	0x42, 0xb2, 0x98, 0xfa, 0x2d, 0x2c, 0xb6, 0x07, 0x83, 0x72, 0xc1, 0x63, 0xea, 0x43, 0xe0, 0x0c,
	0x36, 0x27, 0xf6, 0x60, 0x26, 0x67, 0x9c, 0x69, 0x46, 0xa6, 0x61, 0x44, 0x14, 0x0d, 0x49, 0x6e,
	0xa6, 0xf4, 0xdb, 0x76, 0xf2, 0x8a, 0x3a, 0x26, 0x8a, 0x8e, 0x91, 0xf0, 0x5e, 0xc0, 0x81, 0xa4,
	0x39, 0x61, 0x9c, 0xf1, 0xf4, 0x56, 0x45, 0x07, 0x2b, 0xf6, 0x16, 0xe4, 0x4a, 0xcd, 0x63, 0xe8,
	0x6a, 0xc9, 0xd2, 0x94, 0xca, 0xd0, 0xde, 0xab, 0x8b, 0xf7, 0xea, 0x54, 0xe0, 0x19, 0x5e, 0xef,
	0x29, 0x6c, 0xcf, 0x45, 0x4a, 0x13, 0x5d, 0x2a, 0x7f, 0x1b, 0x55, 0xf3, 0xd2, 0x73, 0x04, 0xbd,
	0xff, 0xc1, 0xa5, 0x97, 0x05, 0x93, 0x33, 0xff, 0x3f, 0x1c, 0xa3, 0x3a, 0x19, 0x5f, 0x63, 0x49,
	0x89, 0xa6, 0x49, 0x48, 0xb4, 0xbf, 0x83, 0x5c, 0xab, 0x42, 0xc6, 0xda, 0x94, 0x55, 0x5d, 0x77,
	0xb1, 0x6b, 0x75, 0xea, 0x7f, 0xaf, 0xc1, 0x36, 0xe6, 0xe0, 0x58, 0x88, 0xec, 0x35, 0xd7, 0x72,
	0x76, 0x7f, 0xb4, 0xd6, 0x84, 0xa5, 0xb6, 0x2e, 0x2c, 0x8b, 0xe7, 0xd8, 0xfc, 0xe7, 0x73, 0xd4,
	0x57, 0x9f, 0x63, 0xad, 0xbd, 0x8d, 0xf5, 0xf6, 0x2e, 0x2d, 0x71, 0x6f, 0x59, 0x12, 0x40, 0x87,
	0xa9, 0xb0, 0x10, 0x4a, 0xdb, 0xa0, 0x6c, 0xd9, 0xa0, 0x30, 0x75, 0x26, 0x94, 0xc6, 0xa0, 0xdc,
	0x9b, 0xa4, 0xdb, 0x69, 0x6d, 0xfd, 0x95, 0xd6, 0xfe, 0xb7, 0x1a, 0xec, 0xe1, 0xeb, 0xbd, 0xa5,
	0x17, 0x74, 0x3a, 0x4e, 0x53, 0x49, 0x53, 0xa2, 0xe9, 0x9d, 0xf5, 0x70, 0xee, 0xae, 0xc7, 0xc2,
	0x94, 0xda, 0xaa, 0x29, 0x01, 0x74, 0x88, 0xca, 0xec, 0xe0, 0xaa, 0xcc, 0xab, 0x05, 0x04, 0xa2,
	0x32, 0x33, 0xef, 0x79, 0x99, 0x9b, 0x05, 0x31, 0x8a, 0xcf, 0xa5, 0xd0, 0x56, 0x52, 0x47, 0x49,
	0x9b, 0xa8, 0xec, 0x9d, 0xc1, 0x8c, 0x26, 0x80, 0x4e, 0xc4, 0x92, 0x65, 0x17, 0xeb, 0x1d, 0x44,
	0x2c, 0x59, 0xe9, 0x62, 0x14, 0xcb, 0x2e, 0xae, 0xed, 0x12, 0xb1, 0x64, 0xd1, 0xe5, 0x10, 0x5a,
	0xe6, 0x9f, 0xf0, 0x21, 0xab, 0x35, 0x6c, 0x12, 0x95, 0xbd, 0x42, 0xcf, 0x0f, 0xa1, 0x65, 0x1a,
	0x58, 0xb2, 0x69, 0xc9, 0x88, 0x25, 0x48, 0xf6, 0x9b, 0xe0, 0x9e, 0x11, 0x49, 0x72, 0x75, 0x7c,
	0xf2, 0xe3, 0xba, 0xe7, 0x5c, 0x5d, 0xf7, 0x9c, 0xdf, 0xd7, 0x3d, 0xe7, 0xeb, 0x4d, 0x6f, 0xe3,
	0xea, 0xa6, 0xb7, 0xf1, 0xeb, 0xa6, 0xb7, 0xf1, 0x61, 0x94, 0x32, 0xfd, 0xa9, 0x8c, 0x86, 0xb1,
	0xc8, 0x47, 0xf3, 0x2f, 0x62, 0xf5, 0xfb, 0x7c, 0x7a, 0x34, 0x5a, 0xfd, 0x3c, 0x1a, 0xef, 0x55,
	0xe4, 0xe2, 0x87, 0xf1, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x2c, 0x62, 0xdd, 0x40,
	0x05, 0x00, 0x00,
}

func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.CreatedAt != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.Expiry != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Expiry))
		i--
		dAtA[i] = 0x78
	}
	if m.TriggerStatus != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.TriggerStatus))
		i--
		dAtA[i] = 0x70
	}
	if m.TriggerPrice != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.TriggerPrice))
		i--
		dAtA[i] = 0x68
	}
	if m.RemainingBaseAmount != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.RemainingBaseAmount))
		i--
		dAtA[i] = 0x60
	}
	if m.InitialBaseAmount != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.InitialBaseAmount))
		i--
		dAtA[i] = 0x58
	}
	if m.Nonce != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x50
	}
	if m.Price != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x48
	}
	if m.ReduceOnly {
		i--
		if m.ReduceOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.TimeInForce != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.TimeInForce))
		i--
		dAtA[i] = 0x38
	}
	if m.OrderType != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OrderType))
		i--
		dAtA[i] = 0x30
	}
	if m.IsAsk {
		i--
		if m.IsAsk {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.MarketIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.MarketIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.OwnerAccountIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OwnerAccountIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.ClientOrderIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.ClientOrderIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.OrderIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OrderIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OrderBookEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderBookEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderBookEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderType != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OrderType))
		i--
		dAtA[i] = 0x48
	}
	if m.ReduceOnly {
		i--
		if m.ReduceOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.IsPostOnly {
		i--
		if m.IsPostOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Expiry != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Expiry))
		i--
		dAtA[i] = 0x30
	}
	if m.RemainingBaseAmount != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.RemainingBaseAmount))
		i--
		dAtA[i] = 0x28
	}
	if m.Nonce != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x20
	}
	if m.Price != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x18
	}
	if m.OwnerAccountIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OwnerAccountIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.OrderIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.OrderIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PriceLevelAggregate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceLevelAggregate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceLevelAggregate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BidCount != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.BidCount))
		i--
		dAtA[i] = 0x40
	}
	if m.AskCount != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x38
	}
	if m.BidQuoteSum != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.BidQuoteSum))
		i--
		dAtA[i] = 0x30
	}
	if m.BidBaseSum != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.BidBaseSum))
		i--
		dAtA[i] = 0x28
	}
	if m.AskQuoteSum != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.AskQuoteSum))
		i--
		dAtA[i] = 0x20
	}
	if m.AskBaseSum != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.AskBaseSum))
		i--
		dAtA[i] = 0x18
	}
	if m.Price != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x10
	}
	if m.MarketIndex != 0 {
		i = encodeVarintOrderbook(dAtA, i, uint64(m.MarketIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintOrderbook(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrderbook(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OrderIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.OrderIndex))
	}
	if m.ClientOrderIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.ClientOrderIndex))
	}
	if m.OwnerAccountIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.OwnerAccountIndex))
	}
	if m.MarketIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.MarketIndex))
	}
	if m.IsAsk {
		n += 2
	}
	if m.OrderType != 0 {
		n += 1 + sovOrderbook(uint64(m.OrderType))
	}
	if m.TimeInForce != 0 {
		n += 1 + sovOrderbook(uint64(m.TimeInForce))
	}
	if m.ReduceOnly {
		n += 2
	}
	if m.Price != 0 {
		n += 1 + sovOrderbook(uint64(m.Price))
	}
	if m.Nonce != 0 {
		n += 1 + sovOrderbook(uint64(m.Nonce))
	}
	if m.InitialBaseAmount != 0 {
		n += 1 + sovOrderbook(uint64(m.InitialBaseAmount))
	}
	if m.RemainingBaseAmount != 0 {
		n += 1 + sovOrderbook(uint64(m.RemainingBaseAmount))
	}
	if m.TriggerPrice != 0 {
		n += 1 + sovOrderbook(uint64(m.TriggerPrice))
	}
	if m.TriggerStatus != 0 {
		n += 1 + sovOrderbook(uint64(m.TriggerStatus))
	}
	if m.Expiry != 0 {
		n += 1 + sovOrderbook(uint64(m.Expiry))
	}
	if m.CreatedAt != 0 {
		n += 2 + sovOrderbook(uint64(m.CreatedAt))
	}
	if m.Status != 0 {
		n += 2 + sovOrderbook(uint64(m.Status))
	}
	return n
}

func (m *OrderBookEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OrderIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.OrderIndex))
	}
	if m.OwnerAccountIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.OwnerAccountIndex))
	}
	if m.Price != 0 {
		n += 1 + sovOrderbook(uint64(m.Price))
	}
	if m.Nonce != 0 {
		n += 1 + sovOrderbook(uint64(m.Nonce))
	}
	if m.RemainingBaseAmount != 0 {
		n += 1 + sovOrderbook(uint64(m.RemainingBaseAmount))
	}
	if m.Expiry != 0 {
		n += 1 + sovOrderbook(uint64(m.Expiry))
	}
	if m.IsPostOnly {
		n += 2
	}
	if m.ReduceOnly {
		n += 2
	}
	if m.OrderType != 0 {
		n += 1 + sovOrderbook(uint64(m.OrderType))
	}
	return n
}

func (m *PriceLevelAggregate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MarketIndex != 0 {
		n += 1 + sovOrderbook(uint64(m.MarketIndex))
	}
	if m.Price != 0 {
		n += 1 + sovOrderbook(uint64(m.Price))
	}
	if m.AskBaseSum != 0 {
		n += 1 + sovOrderbook(uint64(m.AskBaseSum))
	}
	if m.AskQuoteSum != 0 {
		n += 1 + sovOrderbook(uint64(m.AskQuoteSum))
	}
	if m.BidBaseSum != 0 {
		n += 1 + sovOrderbook(uint64(m.BidBaseSum))
	}
	if m.BidQuoteSum != 0 {
		n += 1 + sovOrderbook(uint64(m.BidQuoteSum))
	}
	if m.AskCount != 0 {
		n += 1 + sovOrderbook(uint64(m.AskCount))
	}
	if m.BidCount != 0 {
		n += 1 + sovOrderbook(uint64(m.BidCount))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovOrderbook(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrderbook(x uint64) (n int) {
	return sovOrderbook(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderIndex", wireType)
			}
			m.OrderIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientOrderIndex", wireType)
			}
			m.ClientOrderIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientOrderIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAccountIndex", wireType)
			}
			m.OwnerAccountIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OwnerAccountIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIndex", wireType)
			}
			m.MarketIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAsk", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAsk = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			m.OrderType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeInForce", wireType)
			}
			m.TimeInForce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeInForce |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReduceOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReduceOnly = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBaseAmount", wireType)
			}
			m.InitialBaseAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialBaseAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBaseAmount", wireType)
			}
			m.RemainingBaseAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingBaseAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggerPrice", wireType)
			}
			m.TriggerPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TriggerPrice |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggerStatus", wireType)
			}
			m.TriggerStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TriggerStatus |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			m.Expiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrderbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrderbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderBookEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderBookEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderBookEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderIndex", wireType)
			}
			m.OrderIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAccountIndex", wireType)
			}
			m.OwnerAccountIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OwnerAccountIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBaseAmount", wireType)
			}
			m.RemainingBaseAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingBaseAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			m.Expiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPostOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsPostOnly = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReduceOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReduceOnly = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			m.OrderType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrderbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrderbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PriceLevelAggregate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceLevelAggregate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceLevelAggregate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIndex", wireType)
			}
			m.MarketIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskBaseSum", wireType)
			}
			m.AskBaseSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskBaseSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskQuoteSum", wireType)
			}
			m.AskQuoteSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskQuoteSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidBaseSum", wireType)
			}
			m.BidBaseSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidBaseSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidQuoteSum", wireType)
			}
			m.BidQuoteSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidQuoteSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidCount", wireType)
			}
			m.BidCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BidCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrderbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrderbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderbook
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipOrderbook(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrderbook
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrderbook(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrderbook
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderbook
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrderbook
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrderbook
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrderbook
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrderbook        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrderbook          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrderbook = fmt.Errorf("proto: unexpected end of group")
)
